---
- name: Deploy Database
  hosts: worker2
  vars_files:
    - ../vars/db_creds.yaml
  tasks:
    - name: Deploy Database Server
      become: true
      debug:
        msg:
          "Deploying PostgreSQL database server with the following credentials:
          Username={{ db_user }}"
