services:
  spring-media-service:
    image: 69966/springgradleimg:1.1.1
    container_name: spring_cont_2
    ports:
      - 8081:8080
    volumes:
      - "/mnt/nfs_shared/images2:/app/src/main/resources/images"
  