- name: Install Common Service Playbook
  hosts: worker1, worker2
  become: true
  tasks: 
    - name: Update APT cache
      apt:
        update_cache: yes
    - name: Install Common Packages
      apt:
        name: 
          - nginx
          - fish
          - fastfetch
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
    - name: Create Keyrings Directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Download Docker GPG Keyrings
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
    - name: Add Docker APT Repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ansible_facts.lsb.codename}} stable"
        state: present
        filename: docker
    - name: Update APT Cache After Adding Docker Repository
      apt:
        update_cache: yes
    - name: Install Docker Engine + Compose Plugin
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
    - name: Enable And Start Docker
      service:
        name: docker
        state: started
        enabled: true
    - name: Add Current SSH User To Docker Group
      user:
        name: user
        groups: docker
        append: true
    # - name: Install Neofetch (Optional)
    #   apt:
    #     name: neofetch
    #     state: present
    #   # ignore_errors: true